# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: PRTest
    displayName: PR Test Stage
    jobs:
      - job: PR_Test
      condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.16.x'
          displayName: 'Install Node.js'

        - script: npm install -g @angular/cli
          displayName: 'Install Angular CLI'

        - task: Npm@1
          inputs:
            workingDir: $(System.DefaultWorkingDirectory)/projects/rh-rsa-form-validators
            command: 'install'
          displayName: 'Install package dependencies'

        - task: Npm@1
          inputs:
            workingDir: $(System.DefaultWorkingDirectory)/projects/rh-rsa-form-validators
            command: 'custom'
            customCommand: 'run lint'
          displayName: 'Run eslint checks'

        - task: Npm@1
          inputs:
            workingDir: $(System.DefaultWorkingDirectory)/projects/rh-rsa-form-validators
            command: 'custom'
            customCommand: 'run test'
          displayName: 'Run unit tests'


  - stage: Publish
    displayName: Publish to NPM
    dependsOn: PRTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Publish_to_npm
        steps:
          - task: Npm@1
            inputs:
              workingDir: $(System.DefaultWorkingDirectory)
              command: 'install'
            displayName: 'Install workspace dependencies'

          - task: Npm@1
            inputs:
              workingDir: $(System.DefaultWorkingDirectory)/projects/rh-rsa-form-validators
              command: 'custom'
              customCommand: 'run build'
            displayName: 'Build package'

          - task: Npm@1
            inputs:
              workingDir: $(System.DefaultWorkingDirectory)/dist/rh-rsa-form-validators
              command: 'custom'
              customCommand: 'publish --access public'
              customEndpoint: 'npm_runninghill'
            displayName: 'Publish to npmjs.org'
