# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)/projects/rh-rsa-form-validators
    command: 'install'
  displayName: 'Install dependencies'

- task: Npm@1
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)/projects/rh-rsa-form-validators
    command: 'custom'
    customCommand: 'run lint'
  displayName: 'Run eslint checks'

- task: Npm@1
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)/projects/rh-rsa-form-validators
    command: 'custom'
    customCommand: 'run test'
  displayName: 'Run unit tests'

- task: Npm@1
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)
    command: 'custom'
    customCommand: 'run build'
  displayName: 'Build package'

#- task: Npm@1
#  inputs:
#    command: 'custom'
#    customCommand: 'publish --access public'
#    customEndpoint: 'npm_runninghill'
#  displayName: 'Publish to npmjs.org'
